### ISSUE TITLE
Peer-to-peer Code Review: To-do List Project

### ISSUE THREAD

**Issue by mavericksbalitaan** [MaganaAsiati/do_list#8]
## Hi @MaganaAsiati 😎 

![great-job-good-job](https://user-images.githubusercontent.com/98527559/167568723-83044851-c318-4206-83bf-e5807a990f5f.gif)

### Good Job So Far! 👍 
- [x] Use HTML semantic tags. ✅ 
- [x] Good CSS styling. ✅ 
- [x] Code is clean and dry. ✅ 

### Here are some suggestions:
- [x] We suggest adding MIT.md to the project's repository to make it more professional.
- [x] We suggest updating the links found on the README file to make it descriptive and updated.

---
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
